## Copyright (c) 2022, Oracle and/or its affiliates.
## All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl

### Important Security Notice ###
# The private key generated by this resource will be stored unencrypted in your Terraform state file. 
# Use of this resource for production deployments is not recommended. 
# Instead, generate a private key file outside of Terraform and distribute it securely to the system where Terraform will be run.

output "dev" {
  value = "Made with \u2764 by Oracle Developers"
}

output "deployed_to_region" {
  value = var.region
}
output "deployed_oke_kubernetes_version" {
  value = (var.k8s_version == "Latest") ? local.cluster_k8s_latest_version : var.k8s_version
}
output "kubeconfig_for_kubectl" {
  value       = "export KUBECONFIG=./generated/kubeconfig"
  description = "If using Terraform locally, this command set KUBECONFIG environment variable to run kubectl locally"
}
output "ocir_ocid" {
  value       = oci_artifacts_container_repository.fn_container_repository.id
}
output "queue_dpendpoint" {
  value       = oci_queue_queue.test_queue.messages_endpoint
}
output "ocir_name" {
  value       = oci_artifacts_container_repository.fn_container_repository.display_name
}
output "queue_ocid" {
  value       = oci_queue_queue.test_queue.id
}

